### ISSUE TITLE
What happened to the site?

### ISSUE THREAD

**Issue by nitinthewiz** [chadgmoore/whereTheLightGathers#1]
I had it bookmarked since a long time ago and found it today, and so I discovered that the domain is now gone. Have you moved your writing elsewhere?

I noticed that the writing is preserved in archive.org, which is nice - 

https://web.archive.org/web/20180329201438/http://wherethelightgathers.com/

**Comment by chadgmoore** [comment]
Hello @nitinthewiz 

I let the domain expire, the site is in tact on [http://chad.blot.im/](http://chad.blot.im/) until my blot subscription runs out (July, I think). Yes I've moved my writing over to my [http://blog.chadmoore.net](http://blog.chadmoore.net)

**Comment by chadgmoore** [comment]
I also made the blot theme available via this repo as well.

https://github.com/chadgmoore/whereTheLightGathers-blot
